-- All 93 laws: titles in DE and RO. Rule 31 is skipped (already seeded with full content).
INSERT OR IGNORE INTO rules (number, title_de, title_ro, text_de, text_ro) VALUES
  ('1',  'Kartenpaket', 'Pachetul', '', ''),
  ('2',  'Boards', 'Etuiurile', '', ''),
  ('3',  'Eigenschaften der Tische', 'Dispunerea Meselor', '', ''),
  ('4',  'Partnerschaften', 'Perechile', '', ''),
  ('5',  'Zuweisen der Plätze', 'Așezarea Perechilor la Mese', '', ''),
  ('6',  'Mischen und Teilen', 'Amestecarea și Distribuirea Cărților', '', ''),
  ('7',  'Kontrolle der Boards und Karten', 'Controlul Etuiului și Cărților', '', ''),
  ('8',  'Abfolge der Runden', 'Derularea Rundelor', '', ''),
  ('9',  'Vorgehensweise nach einer Regelwidrigkeit', 'Procedura ca Urmare a unei Neregularități', '', ''),
  ('10', 'Festlegen einer Korrektur', 'Impunerea unei Rectificări', '', ''),
  ('11', 'Verlust des Anspruchs auf Korrektur', 'Pierderea Dreptului la Rectificare', '', ''),
  ('12', 'Ermessensbefugnis des Turnierleiters', 'Puterile Discreționare ale Arbitrului', '', ''),
  ('13', 'Falsche Kartenanzahl', 'Număr Incorect de Cărți', '', ''),
  ('14', 'Fehlende Karte', 'Carte Lipsă', '', ''),
  ('15', 'Falsches Board oder Blatt', 'Donă sau Mână Greșită', '', ''),
  ('16', 'Erlaubte und Unerlaubte Information', 'Informații Autorizate și Neautorizate', '', ''),
  ('17', 'Die Lizitationsphase', 'Perioada de Licitație', '', ''),
  ('18', 'Gebote', 'Anunțuri', '', ''),
  ('19', 'Kontra und Rekontra', 'Contre și Recontre', '', ''),
  ('20', 'Wiederholung und Erklärung von Ansagen', 'Recapitularea și Explicarea Declarațiilor', '', ''),
  ('21', 'Falsche Auskunft', 'Dezinformare', '', ''),
  ('22', 'Ende der Lizitation', 'Sfârșitul Licitației', '', ''),
  ('23', 'Vergleichbare Ansage', 'Declarație Comparabilă', '', ''),
  ('24', 'Während der Lizitation sichtbar gewordene oder ausgespielte Karte', 'Carte Expusă sau Atacată în Timpul Licitației', '', ''),
  ('25', 'Erlaubte und unerlaubte Ansageänderung', 'Schimbări Legale și Ilegale de Declarație', '', ''),
  ('26', 'Zurückgezogene Ansage – Ausspielbeschränkungen', 'Declarație Retrasă, Restricții de Atac', '', ''),
  ('27', 'Ungenügendes Gebot', 'Anunț Insuficient', '', ''),
  ('28', 'Ansagen die als in der Reihe abgegeben gelten', 'Declarații Considerate a Fi la Rând (în Rotație)', '', ''),
  ('29', 'Vorgehensweise nach einer Ansage außer der Reihe', 'Procedura după o Declarație Peste Rând', '', ''),
  ('30', 'Pass außer der Reihe', 'Pas Peste Rând', '', ''),
  ('32', 'Kontra oder Rekontra außer der Reihe', 'Contra sau Recontra Peste Rând', '', ''),
  ('33', 'Gleichzeitige Ansagen', 'Declarații Simultane', '', ''),
  ('34', 'Erhalt des Rechts anzusagen', 'Păstrarea Dreptului de a Declara', '', ''),
  ('35', 'Unzulässige Ansagen', 'Declarații Inadmisibile', '', ''),
  ('36', 'Unzulässiges Kontra oder Rekontra', 'Contre și Recontre Inadmisibile', '', ''),
  ('37', 'Aktion eines Spielers der passen muss', 'Acțiune care Violează Obligația de a Pasa', '', ''),
  ('38', 'Gebot von mehr als sieben', 'Anunț Peste Palierul de 7', '', ''),
  ('39', 'Lizit nach dem abschließenden Pass', 'Declarație după Pas-ul Final', '', ''),
  ('40', 'Partnerschaftsvereinbarungen', 'Înțelegeri între Parteneri', '', ''),
  ('41', 'Beginn des Spiels', 'Începerea Jocului', '', ''),
  ('42', 'Rechte des Strohmanns', 'Drepturile Mortului', '', ''),
  ('43', 'Beschränkungen des Strohmanns', 'Limitări ale Drepturilor Mortului', '', ''),
  ('44', 'Abfolge des Spiels', 'Derularea și Procedura Jocului', '', ''),
  ('45', 'Gespielte Karte', 'Carte Jucată', '', ''),
  ('46', 'Unvollständige oder ungültige Bezeichnung einer Karte des Strohmanns', 'Desemnare Incompletă sau Invalidă a unei Cărți de la Mort', '', ''),
  ('47', 'Zurücknahme einer gespielten Karte', 'Retragerea unei Cărți Jucate', '', ''),
  ('48', 'Sichtbarwerden einer Karte des Alleinspielers', 'Expunerea Cărților Declarantului', '', ''),
  ('49', 'Sichtbarwerden einer Karte eines Gegenspielers', 'Expunerea Cărților unui Apărător', '', ''),
  ('50', 'Vorgehen bei Strafkarten', 'Mod de Utilizare al Cărților Penalizate', '', ''),
  ('51', 'Zwei oder mehr Strafkarten', 'Două sau Mai Multe Cărți Penalizate', '', ''),
  ('52', 'Nichtspielen einer Strafkarte', 'Omisiunea de a Ataca sau Juca o Carte Penalizată', '', ''),
  ('53', 'Angenommenes Ausspiel außer der Reihe', 'Atac Peste Rând Acceptat', '', ''),
  ('54', 'Aufgedecktes Ausspiel außer der Reihe', 'Atac Inițial Peste Rând cu Cartea pe Față', '', ''),
  ('55', 'Ausspiel des Alleinspielers außer der Reihe', 'Atac Peste Rând al Declarantului', '', ''),
  ('56', 'Ausspiel eines Gegenspielers außer der Reihe', 'Atac Peste Rând al unui Apărător', '', ''),
  ('57', 'Vorzeitiges Ausspiel oder Spiel', 'Atac sau Joc Prematur', '', ''),
  ('58', 'Gleichzeitiges Ausspiel oder Spiel', 'Atacuri sau Jocuri Simultane', '', ''),
  ('59', 'Unmöglichkeit wie verlangt auszuspielen', 'Inabilitatea de a Ataca sau Juca Conform Cererii', '', ''),
  ('60', 'Spiel nach einem regelwidrigen Spiel', 'Joc după un Joc Ilegal', '', ''),
  ('61', 'Revoke (wenn nicht Farbe bekannt worden ist)', 'A nu Da la Culoare – Interogări privind Renonsa', '', ''),
  ('62', 'Berichtigung einer Revoke', 'Corectarea unei Renonse', '', ''),
  ('63', 'Etablierte Revoke', 'Consumarea unei Renonse', '', ''),
  ('64', 'Vorgehen bei einer etablierten Revoke', 'Procedura după Consumarea unei Renonse', '', ''),
  ('65', 'Anordnung der Stiche', 'Aranjarea Levatelor', '', ''),
  ('66', 'Stiche ansehen', 'Inspecția Levatelor', '', ''),
  ('67', 'Schadhafter Stich', 'Levată Defectuoasă', '', ''),
  ('68', 'Claim oder Verzicht', 'Revendicare sau Concesie de Levate', '', ''),
  ('69', 'Zustimmung zu Claim oder Verzicht', 'Revendicare sau Concesie Acceptată', '', ''),
  ('70', 'Bestrittener Claim oder Verzicht', 'Revendicare sau Concesie Contestată', '', ''),
  ('71', 'Verzicht aufgehoben', 'Concesie Anulată', '', ''),
  ('72', 'Allgemeine Grundsätze', 'Principii Generale', '', ''),
  ('73', 'Informationsaustausch Tempo und Täuschung', 'Comunicare, Tempo și Inducere în Eroare', '', ''),
  ('74', 'Verhalten und Benehmen', 'Conduită și Etichetă', '', ''),
  ('75', 'Falsche Auskunft oder falsche Ansage', 'Explicație Greșită sau Declarație Greșită', '', ''),
  ('76', 'Zuschauer', 'Spectatori', '', ''),
  ('77', 'Scoretabelle', 'Tabelul de Scor', '', ''),
  ('78', 'Auswertungsmethoden und Austragungsbedingungen', 'Metode de Scor și Condiții de Concurs', '', ''),
  ('79', 'Gewonnene Stiche', 'Levate Câștigate', '', ''),
  ('80', 'Verbandseigene Bestimmungen und Organisation', 'Regulament și Organizare', '', ''),
  ('81', 'Turnierleiter', 'Arbitrul', '', ''),
  ('82', 'Korrektur von Fehlern im Ablauf', 'Rectificarea Erorilor de Procedură', '', ''),
  ('83', 'Hinweis auf das Recht zu berufen', 'Înștiințarea asupra Dreptului de a Face Apel', '', ''),
  ('84', 'Entscheidung bei unstrittigen Tatsachen', 'Decizii asupra unor Fapte Consimțite', '', ''),
  ('85', 'Entscheidung bei umstrittenen Tatsachen', 'Decizii asupra unor Fapte Contestate', '', ''),
  ('86', 'Teamkampf', 'Joc de Echipe', '', ''),
  ('87', 'Vertauschte Partie', 'Donă Incorectă', '', ''),
  ('88', 'Entschädigungspunkte', 'Atribuirea de Puncte de Despăgubire', '', ''),
  ('89', 'Korrekturen im Individualturnier', 'Rectificări în Concursurile Individuale', '', ''),
  ('90', 'Ordnungsstrafen', 'Penalizări Procedurale', '', ''),
  ('91', 'Bestrafung oder Suspendierung', 'Penalizare sau Suspendare', '', ''),
  ('92', 'Berufungen', 'Dreptul de a Face Apel', '', ''),
  ('93', 'Berufungsverfahren', 'Proceduri de Apel', '', '');
